// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOpe05Xv9L0rl8YQ58IWXZwnZHfABOzno',
    appId: '1:1054385282980:web:7e639dbe8f016a27be2b31',
    messagingSenderId: '1054385282980',
    projectId: 'flutter-akademi-155fd',
    authDomain: 'flutter-akademi-155fd.firebaseapp.com',
    databaseURL: 'https://flutter-akademi-155fd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-akademi-155fd.appspot.com',
    measurementId: 'G-6DY4ESG7Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3PN2zc2epeDUOeT2ApPoS2fmkM6D2Qe4',
    appId: '1:1054385282980:android:69511a9f62e863e5be2b31',
    messagingSenderId: '1054385282980',
    projectId: 'flutter-akademi-155fd',
    databaseURL: 'https://flutter-akademi-155fd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-akademi-155fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMBFR6jQRdxthD6Qg6zK2ellRNZveSJw4',
    appId: '1:1054385282980:ios:172cd82431195f4cbe2b31',
    messagingSenderId: '1054385282980',
    projectId: 'flutter-akademi-155fd',
    databaseURL: 'https://flutter-akademi-155fd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-akademi-155fd.appspot.com',
    androidClientId: '1054385282980-72pfav41gvmglcnn4sj8orc4n08r5jf6.apps.googleusercontent.com',
    iosClientId: '1054385282980-mb8foaunn2nh0c06t1gnerc8aohj7isn.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMBFR6jQRdxthD6Qg6zK2ellRNZveSJw4',
    appId: '1:1054385282980:ios:172cd82431195f4cbe2b31',
    messagingSenderId: '1054385282980',
    projectId: 'flutter-akademi-155fd',
    databaseURL: 'https://flutter-akademi-155fd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-akademi-155fd.appspot.com',
    androidClientId: '1054385282980-72pfav41gvmglcnn4sj8orc4n08r5jf6.apps.googleusercontent.com',
    iosClientId: '1054385282980-mb8foaunn2nh0c06t1gnerc8aohj7isn.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled4',
  );
}
